### ISSUE TITLE
Docker Compose not found

### ISSUE THREAD

**Issue by pinage404** [DockStation/dockstation#124]
Hi,

`docker-compose` is not found on [NixOS](https://nixos.org/)

![screenshot_20180630_174519](https://user-images.githubusercontent.com/6325757/42126805-bb0c6ffc-7c8d-11e8-81dc-3a81fc9dc17f.png)

However `docker-compose` is available in the `$PATH`

```sh
$ which docker-compose
# /home/pinage404/.nix-profile/bin/docker-compose
$ echo $PATH
# /run/wrappers/bin:/etc/profiles/per-user/pinage404/bin:/home/pinage404/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
```

**Comment by igor-lemon** [comment]
Hi @pinage404 Thanks for the issue. Maybe you can try to make a symlink for docker-compose into
`/usr/local/bin/` or `/usr/bin/`

**Comment by igor-lemon** [comment]
So, It should work. You use AppImages. Do you run the app with `sudo ...` via `root` user or without via `pinage404` user?

**Comment by pinage404** [comment]
I run it with `pinage404` user using the [`appimage-run` command line](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/package-management/appimage-run/default.nix) (who basically extract the appimage in a folder and run it)

**Comment by igor-lemon** [comment]
It's strange. Ok, I'll try to install NixOS and repeat your issue.

**Comment by pinage404** [comment]
I had the same kind of issue with VSCode, they fixed it with this https://github.com/microsoft/vscode/commit/0bab532a332c9e4390c735f99e19db2821adab36

**Comment by jakabk** [comment]
Same problem on Debian Buster.
Dockstation version 1.5.1

![image](https://user-images.githubusercontent.com/7803077/94235890-943df400-ff0c-11ea-87ca-d71669b1c426.png)

![image](https://user-images.githubusercontent.com/7803077/94236156-09a9c480-ff0d-11ea-9fe2-14bb84065336.png)

**Comment by igor-lemon** [comment]
Hi. What is the rights and user/user group do you have for Docker Compose?

**Comment by jakabk** [comment]
@igor-lemon 
ls -la /usr/bin/docker-compose 
-rwxr-xr-x 1 root root 420 Oct  3  2018 /usr/bin/docker-compose

**Comment by nohupped** [comment]
I had the same issue on my arch linux, and I was able to fix it by clearing my local sitepackages which was conflicting with the global packages.

I had docker-compose in my `$PATH`
```
[ 24-11-20::14:02:39 ] ❯ which docker-compose
/usr/bin/docker-compose

```
When I ran dockstation from my commandline, I was seeing the same error 

```
Docker compose not installed
```
and I was seeing the following error in my terminal.

```
~ via 🐹 v1.15.5 via 🐍 v3.8.6 via 🦀 v1.46.0 
[ 24-11-20::13:58:16 ] ❯ dockstation 
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.27.4', 'console_scripts', 'docker-compose')())
  File "/usr/bin/docker-compose", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 41, in <module>
    from .command import get_config_from_options
  File "/usr/lib/python3.8/site-packages/compose/cli/command.py", line 13, in <module>
    from .docker_client import get_client
  File "/usr/lib/python3.8/site-packages/compose/cli/docker_client.py", line 6, in <module>
    from docker import Context
ImportError: cannot import name 'Context' from 'docker' (/home/nohup/.local/lib/python3.8/site-packages/docker/__init__.py)

```

This was my per-user site-packages path

```
[ 24-11-20::14:04:13 ] ❯ python -m site --user-site
/home/nohup/.local/lib/python3.8/site-packages

```
Since I never used them, it was safe for me to delete `/home/nohup/.local/lib/python3.8/site-packages` and after that, dockstation started working for me and detected docker-compose.

Just posting it here, in case if it helps someone.

**Comment by Lewenhaupt** [comment]
Just faced this issue on a fresh install of Ubuntu-budgie, any solution?

EDIT: it appears the reinit application button doesn't actually work a 100%. Restarting the application made it detect docker-compose

**Comment by siourdas-vasilis** [comment]
> Just faced this issue on a fresh install of Ubuntu-budgie, any solution?
> 
> EDIT: it appears the reinit application button doesn't actually work a 100%. Restarting the application made it detect docker-compose

Same for me on Ubuntu 20.04.2 LTS

**Comment by Lerke** [comment]
Running into the same problem after upgrading to Docker for Windows 3.4.0. Dockstation reports that Docker Compose is not installed, but running `docker-compose` (or `docker compose`) via the command line works fine.

**Comment by pierreveys** [comment]
> Running into the same problem after upgrading to Docker for Windows 3.4.0. Dockstation reports that Docker Compose is not installed, but running `docker-compose` (or `docker compose`) via the command line works fine.

Hi, just faced the same issue after I updated Docker to the last version 3.5.1. Dockstation version is 1.5.1.
I'm on MacOs 11.4 and `docker-compose` is working just fine via the command line.

`which docker-compose`
return
`/usr/local/bin/docker-compose` which is actually `/Applications/Docker.app/Contents/Resources/bin/docker-compose`

**Comment by vinihagemeister** [comment]
Hey broo!!! i'm on Windows we solved by disabling "use Docker Copose V2" in Settings "Experimental Features" into Docker.

![docker](https://user-images.githubusercontent.com/33074126/125963700-85da5ea6-08ea-47c4-9a02-3648d26969b3.png)

**Comment by acjvenis** [comment]
The same applies to the MacOS version; disabling the option in the and restarting resolves the error. Thanks!

**Comment by karthikeyana** [comment]
I have installed this way it work for me.

```
sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)"  -o /usr/local/bin/docker-compose
sudo mv /usr/local/bin/docker-compose /usr/bin/docker-compose
sudo chmod +x /usr/bin/docker-compose
```

**Comment by ghost** [comment]
Have the same issue on my Manjaro KDE:
```sh
❯ where docker-compose 
/usr/bin/docker-compose

❯ docker-compose --version
Docker Compose version 2.2.3
```
There should be a way to at least provide a path to `docker-compose` if it's such a common problem.

**Comment by rpsmendes** [comment]
> I have installed this way it work for me.
> 
> ```
> sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)"  -o /usr/local/bin/docker-compose
> sudo mv /usr/local/bin/docker-compose /usr/bin/docker-compose
> sudo chmod +x /usr/bin/docker-compose
> ```

Also worked for me. Thanks!

**Comment by desiderati** [comment]
> .local/lib/python3.8/site-packages

This is an old version that should not have been used anymore.

**Comment by desiderati** [comment]
> I have installed this way it work for me.
> 
> ```
> sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)"  -o /usr/local/bin/docker-compose
> sudo mv /usr/local/bin/docker-compose /usr/bin/docker-compose
> sudo chmod +x /usr/bin/docker-compose
> ```

This is an old version that should not have been used anymore.
