### ISSUE TITLE
How to choose docker-compose binary ?

### ISSUE THREAD

**Issue by boskiv** [DockStation/dockstation#146]
Is there way to choose executable file for docker-compose on Windows
Or path (venv) to use it on OSX ?
Because I have on OSX an error
```
Failed to fetch container logs: 
Command failed: /usr/local/bin/docker-compose -f docker-compose.yml -p test logs --tail=1000 mongo 2>&1

[stdout]: Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in 
    load_entry_point('docker-compose==1.22.0', 'console_scripts', 'docker-compose')()
  File "/usr/local/Cellar/docker-compose/1.22.0_2/libexec/lib/python3.7/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/local/Cellar/docker-compose/1.22.0_2/libexec/lib/python3.7/site-packages/compose/cli/main.py", line 124, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/Cellar/docker-compose/1.22.0_2/libexec/lib/python3.7/site-packages/compose/cli/command.py", line 41, in project_from_options
    compatibility=options.get('--compatibility'),
  File "/usr/local/Cellar/docker-compose/1.22.0_2/libexec/lib/python3.7/site-packages/compose/cli/command.py", line 126, in get_project
    project_name, config_data, client, environment.get('DOCKER_DEFAULT_PLATFORM')
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/Cellar/docker-compose/1.22.0_2/libexec/lib/python3.7/site-packages/compose/cli/errors.py", line 53, in handle_connection_errors
    exit_with_error(get_conn_error_message(client.base_url))
  File "/usr/local/Cellar/docker-compose/1.22.0_2/libexec/lib/python3.7/site-packages/compose/cli/errors.py", line 120, in get_conn_error_message
    if find_executable('docker') is None:
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/spawn.py", line 176, in find_executable
    path = os.environ['PATH']
  File "/usr/local/Cellar/docker-compose/1.22.0_2/libexec/bin/../lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'PATH'
```

On WIndows it drop an error 
```
file not found
```

**Comment by igor-lemon** [comment]
Hi @boskiv 
No, we don't have this option.
The app checks all `$PATH` paths and looking for `docker-compose` file. 

The solutions
1) Check all export directories. `echo $PATH` Set your custom directory first than `/usr/local/bin`.
Finally result should be some as `/Users/igor/.rbenv/shims:/Users/igor/.fastlane/bin:/Users/igor/Library/Android/sdk/platform-tools:/Users/igor/.nvm/versions/node/v9.11.1/bin:/YOUR_CUSTOM_DIR:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/`...

2)  Set symlink from your custom docker-compose to default bin directory `ln -sf /CUSTOM_DIR/docker-compose /usr/local/bin/docker-compose`

Unfortunately, I can't say anything about Windows but I think you can reproduce it similarly.

**Comment by igor-lemon** [comment]
But in your log the problem isn't relating with the path of Docker Compose.

**Comment by boskiv** [comment]
Yeah, thanks. I will try to check my envs.

**Comment by boskiv** [comment]
This how it's look on windows. docker-compose works fine from powershell or cmd.
envs are set right.
docker, docker-compose, docker-machine was installed with choco
```
choco install docker docker-compose docker-machine
```
![screenshot 2018-10-24 at 9 17 22 am](https://user-images.githubusercontent.com/1939783/47410263-e220af00-d76d-11e8-867b-f524306e5705.png)

**Comment by boskiv** [comment]
Ok, I have run process explorer and there is an env:
![screenshot 2018-10-24 at 9 31 58 am](https://user-images.githubusercontent.com/1939783/47410834-be5e6880-d76f-11e8-85f7-b542aea436c1.png)

**Comment by igor-lemon** [comment]
I'll try to check your case. I can't do it now because I don't have a Windows PC.
I will definitely let you know results.

**Comment by boskiv** [comment]
I'm using Virtual Machine with Windows in cases like this.

**Comment by igor-lemon** [comment]
So, Do I understand you that
1) You've Virtual Machine with Windows 10? 
2) You're using Docker Machine in the VM?

**Comment by boskiv** [comment]
Yes. I have Paralles VM with Windows 10.
I have Orace virtualbox inside Windows 10.
I'm testing solution for our developers more convenient to work with docker. So I have this environment. But It should not be a problem because of isolation.
Nested virtualisation enabled of cause. And docker also work from command line.

**Comment by igor-lemon** [comment]
Do you use Docker for Windows or Docker toolbox ?

**Comment by boskiv** [comment]
I think nothing of it. I have install docker from choco package manager. There is just docker client, docker-machine and docker-compose binaries

**Comment by igor-lemon** [comment]
So we reproduced your problem and found the same issues. You didn't start Docker daemon.
https://github.com/docker/toolbox/issues/725

But unfortunately, I can't say anything about your case with choco package manager. We'll try to check it a bit later. 
At the moment I can recommend to instal and use the latest version Docker For Windows.

**Comment by igor-lemon** [comment]
Huh. We found and fixed one bug which reproduced with Docker Toolbox only for Windows. This is bug very similar with your case, but I can't promise it will able to resolve your issue.

**Comment by boskiv** [comment]
Thanks, Igor. I will try, but I have docker daemon inside my Oracle docker-machine created VM, why I need to have one on Windows.
And I have docker-compose up working in PowerSHell without local daemon started
```
PS C:\Users\i_skiridomov> docker-machine start
Starting "default"...
(default) Check network to re-create if needed...
(default) Windows might ask for the permission to configure a dhcp server. Sometimes, such confirmation window is minimized in the taskbar.
(default) Waiting for an IP...
Machine "default" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
PS C:\Users\i_skiridomov> docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
PS C:\Users\i_skiridomov> docker-coma^C
PS C:\Users\i_skiridomov> cd .\Documents\
PS C:\Users\i_skiridomov\Documents> cd .\Demo\
PS C:\Users\i_skiridomov\Documents\Demo> .\docker-compose.yml^C
PS C:\Users\i_skiridomov\Documents\Demo> docker-compose up
Creating network "demo_default" with the default driver
Pulling mysql (mysql:)...
latest: Pulling from library/mysql
f17d81b4b692: Pull complete
c691115e6ae9: Pull complete
41544cb19235: Pull complete
254d04f5f66d: Pull complete
4fe240edfdc9: Pull complete
0cd4fcc94b67: Extracting [========================>                          ]  6.029MB/12.09MB
8df36ec4b34a: Download complete
720bf9851f6a: Download complete

9ffdbf5f677f: Download complete
a403e1df0389: Waiting
4669c5f285a6: Waiting




```

**Comment by boskiv** [comment]
Building images also works fine
```
PS C:\Users\i_skiridomov\Documents\Demo> docker-compose up
Building custom
Step 1/1 : FROM nginx
latest: Pulling from library/nginx
f17d81b4b692: Already exists
d5c237920c39: Pull complete
a381f92f36de: Pull complete
Digest: sha256:b73f527d86e3461fd652f62cf47e7b375196063bbbd503e853af5be16597cb2e
Status: Downloaded newer image for nginx:latest
 ---> dbfc48660aeb

Successfully built dbfc48660aeb
Successfully tagged demo_custom:latest
WARNING: Image for service custom was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Starting demo_mysql_1  ... done
Creating demo_custom_1 ... done
Attaching to demo_mysql_1, demo_custom_1
mysql_1   | error: database is uninitialized and password option is not specified
mysql_1   |   You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
demo_mysql_1 exited with code 1
```

**Comment by boskiv** [comment]
All I need to works with is env:
```
PS C:\Users\i_skiridomov\Documents\Demo> Get-ChildItem env:

Name                           Value
----                           -----
DOCKER_CERT_PATH               C:\Users\i_skiridomov\.docker\machine\machines\default
DOCKER_HOST                    tcp://192.168.99.100:2376
DOCKER_MACHINE_NAME            default
DOCKER_TLS_VERIFY              1
PS C:\Users\i_skiridomov\Documents\Demo>
```

**Comment by igor-lemon** [comment]
So, I think this is the bug which we fixed yesterday. I'll try to build a temporary build. Will you able to check it?

**Comment by boskiv** [comment]
Sure I will, thanks.

**Comment by igor-lemon** [comment]
Please write me to igor@dockstation.io I'll send you a pre-release version for test.

**Comment by guzart** [comment]
Hello @igor-lemon, 

Could this issue be the same as the one reported by [jacoblyw](https://github.com/DockStation/dockstation/issues/149#issuecomment-438204660)? I am having the same issue `KeyError: 'PATH'` on OS 10.14.

**Comment by igor-lemon** [comment]
Hi @guzart. I'll try to find a solution today.
