### ISSUE TITLE
KeyError: 'PATH' on OSX 10.14

### ISSUE THREAD

**Issue by boskiv** [DockStation/dockstation#149]
```
Failed to fetch container logs: 
Command failed: /usr/local/bin/docker-compose -f docker-compose.yml -p devenv logs --tail=1000 mgr 2>&1

[stdout]: Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in 
    load_entry_point('docker-compose==1.22.0', 'console_scripts', 'docker-compose')()
  File "/usr/local/Cellar/docker-compose/1.22.0_2/libexec/lib/python3.7/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/local/Cellar/docker-compose/1.22.0_2/libexec/lib/python3.7/site-packages/compose/cli/main.py", line 124, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/Cellar/docker-compose/1.22.0_2/libexec/lib/python3.7/site-packages/compose/cli/command.py", line 41, in project_from_options
    compatibility=options.get('--compatibility'),
  File "/usr/local/Cellar/docker-compose/1.22.0_2/libexec/lib/python3.7/site-packages/compose/cli/command.py", line 126, in get_project
    project_name, config_data, client, environment.get('DOCKER_DEFAULT_PLATFORM')
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/Cellar/docker-compose/1.22.0_2/libexec/lib/python3.7/site-packages/compose/cli/errors.py", line 53, in handle_connection_errors
    exit_with_error(get_conn_error_message(client.base_url))
  File "/usr/local/Cellar/docker-compose/1.22.0_2/libexec/lib/python3.7/site-packages/compose/cli/errors.py", line 120, in get_conn_error_message
    if find_executable('docker') is None:
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/spawn.py", line 176, in find_executable
    path = os.environ['PATH']
  File "/usr/local/Cellar/docker-compose/1.22.0_2/libexec/bin/../lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'PATH'
```

![screenshot 2018-10-30 at 12 19 49 pm](https://user-images.githubusercontent.com/1939783/47711538-23b5cc00-dc3e-11e8-96da-b46166651124.png)

**Comment by jacoblyw** [comment]
Getting _KeyError: 'PATH'_ also.

Mac OS 10.12.6, 
Docker Mac Version 18.06.0-ce-mac70 (26399)
Engine: 18.06.0-ce
Compose: 1.22.0
Machine: 0.15.0

```
Building web
[54498] Failed to execute script docker-compose
Traceback (most recent call last):
File "docker-compose", line 6, in
File "compose/cli/main.py", line 71, in main
File "compose/cli/main.py", line 127, in perform_command
File "compose/cli/main.py", line 1052, in up
File "compose/cli/main.py", line 1048, in up
File "compose/project.py", line 471, in up
File "compose/service.py", line 352, in ensure_image_exists
File "compose/service.py", line 1067, in build
File "site-packages/docker/api/build.py", line 251, in build
File "site-packages/docker/api/build.py", line 306, in _set_auth_headers
File "site-packages/docker/auth. py", line 96, in resolve_authcontig
File “site-packages/docker/auth. py", line 127, in _resolve_authconfig_credstore
File "site-packages/dockerpycreds/store.py", line 20, in __init__
File "site-packages/dockerpycreds/utils.py", line 12, in find_executable
File "distutils/spawn.py", line 176, in find_executable
File "os.py", line 669, in __getitem__
KeyError: ‘PATH'
child process exited with code 255

```

_docker-compose_ and _docker up -d_ from command line works just fine.

**Comment by igor-lemon** [comment]
Hi guys! Ok. I'll try to find a solution to resolve this trouble.

**Comment by igor-lemon** [comment]
@boskiv @jacoblyw 
Please write me your `~/.docker/config.json`

**Comment by boskiv** [comment]
I don't have 
```
➜  .docker ls -al
total 8
drwx------   4 i_skiridomov  staff   128 Nov 14 12:52 .
drwxr-xr-x+ 62 i_skiridomov  staff  1984 Nov 14 17:01 ..
-rw-------   1 i_skiridomov  staff    64 Nov 14 12:52 .buildNodeID
drwx------   5 i_skiridomov  staff   160 Nov  2 00:56 machine
➜  .docker 
```

Just check from scratch setup. Same error.
P.S. I dont use Docker For Mac. I have setup it from brew
```
brew install docker docker-machine docker-compose
```

**Comment by jacoblyw** [comment]
`~/.docker/config.json`
```
{
  "credSstore" : "osxkeychain",
  "auths" : {
    "https://index.docker.io/v1/" : {

    }
  },
  "credsStore" : "osxkeychain"
}
```

**Comment by igor-lemon** [comment]
@boskiv @jacoblyw
Please write me `.env` file from yours projects directories.
Let's try to add into this file 
`PATH=$PATH`

**Comment by igor-lemon** [comment]
Huh, I think this error relates with #146 issue, which will be fixed in v1.5

@boskiv Can you check this case on the pre-release version too?

**Comment by boskiv** [comment]
@igor-lemon I have only windows build, can you send me OSX build as well ?

**Comment by igor-lemon** [comment]
Sure. I'll build and send you the app today.

**Comment by igor-lemon** [comment]
Hi @boskiv @jacoblyw 
Can you help me to check a pre-release version?
Because I couldn't reproduce this bug on my side, I need your help.

**Comment by jacoblyw** [comment]
@igor-lemon Yes, I can (sorry for the delay)

Tell me what to do
