### ISSUE TITLE
Can't use Dockstation to exec containers due to bad DOCKER_HOST env on OSX due to docker.errors.DockerException: Invalid bind address format 

### ISSUE THREAD

**Issue by funkytaco** [DockStation/dockstation#205]
I am getting the error `docker.errors.DockerException: Invalid bind address format` unless I unset DOCKER_HOST from shell, but this does not fix the issue for Dockstation.

Here is the bad env setting:
```
~/Git/DockStation/RemoteJobs  env|grep DOCKER
DOCKER_HOST=-H unix:///var/run/docker.sock -H tcp://localhost:2376
```

I cannot find where DOCKER_HOST is set. I've already reset Docker.app. I've tried adding to .bash_profile as unset as well.

Dockstation returns the following error. I know the problem is DOCKER_HOST on OSX is set incorrectly (I have to `unset DOCKER_HOST` for it to work from the command line). 

Example from shell:

```
/usr/local/bin/docker-compose -f "docker-compose.yml" -p remotejobs logs --tail=500 jenkins 2>&1
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/command.py", line 42, in project_from_options
  File "compose/cli/command.py", line 123, in get_project
  File "compose/cli/command.py", line 94, in get_client
  File "compose/cli/docker_client.py", line 127, in docker_client
  File "site-packages/docker/api/client.py", line 133, in __init__
  File "site-packages/docker/utils/utils.py", line 288, in parse_host
docker.errors.DockerException: Invalid bind address format: port is required: -H unix:///var/run/docker.sock -H tcp://localhost:2376
[48823] Failed to execute script docker-compose
```

 **\#~/Git/DockStation/RemoteJobs  unset DOCKER_HOST**

Unsetting it fixes it on the shell, but not Dockerstation:

```
 \# ~/Git/DockStation/RemoteJobs  /usr/local/bin/docker-compose -f "docker-compose.yml" -p remotejobs logs --tail=500 jenkins 2>&1
Attaching to remotejobs_jenkins_1
jenkins_1  | Running from: /usr/share/jenkins/jenkins.war
jenkins_1  | webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
jenkins_1  | Aug 12, 2019 11:04:57 PM Main deleteWinstoneTempContents
jenkins_1  | WARNING: Failed to delete the temporary Winstone file /tmp/winstone/jenkins.war
jenkins_1  | Aug 12, 2019 11:04:57 PM org.eclipse.jetty.util.log.JavaUtilLog info
jenkins_1  | INFO: Logging initialized @405ms
jenkins_1  | Aug 12, 2019 11:04:57 PM winstone.Logger logInternal
jenkins_1  | INFO: Beginning extraction from war file
jenkins_1  | Aug 12, 2019 11:04:58 PM org.eclipse.jetty.util.log.JavaUtilLog warn
jenkins_1  | WARNING: Empty contextPath
jenkins_1  | Aug 12, 2019 11:04:58 PM org.eclipse.jetty.util.log.JavaUtilLog info
jenkins_1  | INFO: jetty-9.2.z-SNAPSHOT
jenkins_1  | Aug 12, 2019 11:04:58 PM org.eclipse.jetty.util.log.JavaUtilLog info
jenkins_1  | INFO: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
jenkins_1  | Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
jenkins_1  | Aug 12, 2019 11:04:59 PM org.eclipse.jetty.util.log.JavaUtilLog info
jenkins_1  | INFO: Started w.@47404bea{/,file:/var/jenkins_home/war/,AVAILABLE}{/var/jenkins_home/war}
jenkins_1  | Aug 12, 2019 11:04:59 PM org.eclipse.jetty.util.log.JavaUtilLog info
jenkins_1  | INFO: Started ServerConnector@458342d3{HTTP/1.1}{0.0.0.0:8080}
jenkins_1  | Aug 12, 2019 11:04:59 PM org.eclipse.jetty.util.log.JavaUtilLog info
jenkins_1  | INFO: Started @2578ms
jenkins_1  | Aug 12, 2019 11:04:59 PM winstone.Logger logInternal
jenkins_1  | INFO: Winstone Servlet Engine v2.0 running: controlPort=disabled
jenkins_1  | Aug 12, 2019 11:04:59 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Started initialization
jenkins_1  | Aug 12, 2019 11:04:59 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Listed all plugins
jenkins_1  | Aug 12, 2019 11:05:00 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Prepared all plugins
jenkins_1  | Aug 12, 2019 11:05:00 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Started all plugins
jenkins_1  | Aug 12, 2019 11:05:00 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Augmented all extensions
jenkins_1  | Aug 12, 2019 11:05:01 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Loaded all jobs
jenkins_1  | Aug 12, 2019 11:05:01 PM hudson.model.AsyncPeriodicWork$1 run
jenkins_1  | INFO: Started Download metadata
jenkins_1  | Aug 12, 2019 11:05:02 PM jenkins.util.groovy.GroovyHookScript execute
jenkins_1  | INFO: Executing /var/jenkins_home/init.groovy.d/tcp-slave-agent-port.groovy
jenkins_1  | Aug 12, 2019 11:05:02 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Completed initialization
jenkins_1  | Aug 12, 2019 11:05:02 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
jenkins_1  | INFO: Refreshing org.springframework.web.context.support.StaticWebApplicationContext@2c2c29d7: display name [Root WebApplicationContext]; startup date [Mon Aug 12 23:05:02 UTC 2019]; root of context hierarchy
jenkins_1  | Aug 12, 2019 11:05:02 PM org.springframework.context.support.AbstractApplicationContext obtainFreshBeanFactory
jenkins_1  | INFO: Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@2c2c29d7]: org.springframework.beans.factory.support.DefaultListableBeanFactory@6766a9b4
jenkins_1  | Aug 12, 2019 11:05:02 PM org.springframework.beans.factory.support.DefaultListableBeanFactory preInstantiateSingletons
jenkins_1  | INFO: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@6766a9b4: defining beans [authenticationManager]; root of factory hierarchy
jenkins_1  | Aug 12, 2019 11:05:02 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
jenkins_1  | INFO: Refreshing org.springframework.web.context.support.StaticWebApplicationContext@640df7ff: display name [Root WebApplicationContext]; startup date [Mon Aug 12 23:05:02 UTC 2019]; root of context hierarchy
jenkins_1  | Aug 12, 2019 11:05:02 PM org.springframework.context.support.AbstractApplicationContext obtainFreshBeanFactory
jenkins_1  | INFO: Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@640df7ff]: org.springframework.beans.factory.support.DefaultListableBeanFactory@2ee3084f
jenkins_1  | Aug 12, 2019 11:05:02 PM org.springframework.beans.factory.support.DefaultListableBeanFactory preInstantiateSingletons
jenkins_1  | INFO: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@2ee3084f: defining beans [filter,legacy]; root of factory hierarchy
jenkins_1  | Aug 12, 2019 11:05:02 PM jenkins.install.SetupWizard init
jenkins_1  | INFO: 
jenkins_1  | 
jenkins_1  | *************************************************************
jenkins_1  | *************************************************************
jenkins_1  | *************************************************************
jenkins_1  | 
jenkins_1  | Jenkins initial setup is required. An admin user has been created and a password generated.
jenkins_1  | Please use the following password to proceed to installation:
jenkins_1  | 
jenkins_1  | 20c7352650b14bdd9b37274dbd87fe5f
jenkins_1  | 
jenkins_1  | This may also be found at: /var/jenkins_home/secrets/initialAdminPassword
jenkins_1  | 
jenkins_1  | *************************************************************
jenkins_1  | *************************************************************
jenkins_1  | *************************************************************
jenkins_1  | 
jenkins_1  | Aug 12, 2019 11:05:06 PM hudson.model.UpdateSite updateData
jenkins_1  | INFO: Obtained the latest update center data file for UpdateSource default
jenkins_1  | Aug 12, 2019 11:05:06 PM hudson.model.DownloadService$Downloadable load
jenkins_1  | INFO: Obtained the updated data file for hudson.tasks.Maven.MavenInstaller
jenkins_1  | Aug 12, 2019 11:05:07 PM hudson.model.DownloadService$Downloadable load
jenkins_1  | INFO: Obtained the updated data file for hudson.tools.JDKInstaller
jenkins_1  | Aug 12, 2019 11:05:07 PM hudson.model.AsyncPeriodicWork$1 run
jenkins_1  | INFO: Finished Download metadata. 5,462 ms
jenkins_1  | Aug 12, 2019 11:05:08 PM hudson.model.UpdateSite updateData
jenkins_1  | INFO: Obtained the latest update center data file for UpdateSource default
jenkins_1  | Aug 12, 2019 11:05:08 PM hudson.WebAppMain$3 run
jenkins_1  | INFO: Jenkins is fully up and running
jenkins_1  | --> setting agent port for jnlp
jenkins_1  | --> setting agent port for jnlp... done
```

**Comment by funkytaco** [comment]
Additionally, if I try to exec into the container, I get `unable to resolve docker endpoint: Invalid bind address format: -H unix:///var/run/docker.sock -H tcp://localhost:2376` due to this env problem. I can't find where this is set on OSX.

**Comment by igor-lemon** [comment]
Hi @funkytaco I'll check your case on my machine and write results
