### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by azumukupoe** [DockStation/dockstation#301]
```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: spawn wmic.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

[OK]
```

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: Cannot read property 'forEach' of undefined
    at Stream.<anonymous> (C:\Program Files\DockStation\resources\app.asar\webpack:\app\main.prod.js:1:1)
    at Stream.emit (events.js:182:13)
    at Stream.i (C:\Program Files\DockStation\resources\app.asar\webpack:\app\main.prod.js:308:1)
    at Stream.emit (events.js:187:15)
    at f (C:\Program Files\DockStation\resources\app.asar\webpack:\app\main.prod.js:85:1)
    at Stream.n.write (C:\Program Files\DockStation\resources\app.asar\webpack:\app\main.prod.js:85:1)
    at Stream.ondata (internal/streams/legacy.js:15:31)
    at Stream.emit (events.js:182:13)
    at l (C:\Program Files\DockStation\resources\app.asar\webpack:\app\main.prod.js:308:1)
    at Stream.u.queue.u.push (C:\Program Files\DockStation\resources\app.asar\webpack:\app\main.prod.js:308:1)
    at u (C:\Program Files\DockStation\resources\app.asar\webpack:\app\main.prod.js:41:1)
    at Stream.<anonymous> (C:\Program Files\DockStation\resources\app.asar\webpack:\app\main.prod.js:41:1)
    at Stream.u.end (C:\Program Files\DockStation\resources\app.asar\webpack:\app\main.prod.js:308:1)
    at Socket.onend (_stream_readable.js:628:10)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:187:15)

[OK]
```

**Comment by igor-lemon** [comment]
Hi! What is Windows version?

**Comment by azumukupoe** [comment]
Windows 10 Pro 19044.1415

**Comment by azumukupoe** [comment]
nvm I think it was a problem on my end
messing around with environment variables fixed it
